version: '3.8'
services:
    db:
        container_name: poc_db
        image: postgres
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
